### ISSUE TITLE
مشکل در ست کردن تاریخ شمسی با ساعت

### ISSUE THREAD

**Issue by mnouraei** [babakhani/persian-datepicker-next-version#10]
سلام
من به این صورت مقدارم تاریخ پیش فرض را شمسی ست میکنم، اما تاریخ جاری سیستم را برای من برمیگرداند
لطفا راهنمایی بفرمایید

`    <input class="initial-value-type-example" value="1400/02/08 19:24:00" />

    <script>
        $('.initial-value-type-example').pDatepicker({
            initialValueType:'persian',
            format: 'YYYY/MM/DD HH:mm:ss',
        })
    </script>`

**Comment by mort3za** [comment]
Hi, I don't see your default date in your example.  It should be on your input tag. Check this example please: https://codepen.io/mort3za/pen/oNYPBem

**Comment by mnouraei** [comment]
Hi, Please Set value="1396-10-12 12:20" and check return value

**Comment by mort3za** [comment]
It doesn't accept time in the current version. You should use setDate to set datetime. Pen updated. https://codepen.io/mort3za/pen/oNYPBem

Please open other issues in the main repo. This repo is temporary, for next version.

**Comment by mnouraei** [comment]
tnx,
